
GET http://localhost:3003/api/blogs
Content-Type: application/json

###

POST http://localhost:3003/api/blogs
Content-Type: application/json


{
  "title": "Testi",
  "author": "Lamba chahe",
  "url": "www.testi.com",
  "likes": 5
}

###

DELETE http://localhost:3003/api/blogs/6a159094a956585daf52d45b
Content-Type: application/json